### ISSUE TITLE
Slack.find().count() >= 1

### ISSUE THREAD

**Issue by wiiiimm** [studiointeract/meteor-slack-invite#1]
In https://github.com/studiointeract/meteor-slack-invite/blob/master/slack-invite.js#L5
why do you check Slack.find().count() === 1 ?
I deployed this on meteor.com and found that Slack.find().count() will increase as time goes by and the check for === 1 kills the package

**Comment by wiiiimm** [comment]
found the root of the problem:
the code 
`Slack.upsert({_id: 'slack'}, data);`
created records like 

{ "_id" : ObjectId("55627cb29afaac497f33df4b"), "online" : 2, "registered" : 3, "name" : "EYE", "domain" : "eye" }
{ "_id" : ObjectId("55627cca9afaac497f33df4e"), "online" : 2, "registered" : 3, "name" : "EYE", "domain" : "eye" }
{ "_id" : ObjectId("55627ce89afaac497f33df50"), "online" : 2, "registered" : 3, "name" : "EYE", "domain" : "eye" }
{ "_id" : ObjectId("55627d069afaac497f33df52"), "online" : 2, "registered" : 3, "name" : "EYE", "domain" : "eye" }

on the meteor mongo server

**Comment by wiiiimm** [comment]
fixed in this pull request https://github.com/studiointeract/meteor-slack-invite/pull/2

**Comment by timbrandin** [comment]
Hi, you should check out http://github.com/SpaceTalk/SpaceTalk, we've started working on the next version over there. Cheers // Tim

**Comment by timbrandin** [comment]
Merged in af9a45f05a076ea9b1f39fbf9940405bf85c03d4 and in latest version 1.0.3
